### ISSUE TITLE
Your test seems wrong, testCalculateTermInDocumentFrequency2

### ISSUE THREAD

**Issue by PhilAndrew** [dbousamra/search-engine-scala#1]
From the following code:

 def testCalculateTermInDocumentFrequency2() = {
    val searchRanker = new SearchRanker(new InvertedIndex[MockDocument])
    val document = documentManager.parse(new File("./src/resources/documents/bible/Genesis.txt"))

```
val rank = searchRanker.index.tf("moses", document)
println("Rank = " + rank)
```

I get the value of 1.0 out.

**Comment by dbousamra** [comment]
Very possible (likely) that it's wrong. I haven't touched this code in over a year.

**Comment by PhilAndrew** [comment]
I want a basic text search engine in-memory (no disk access) in-Scala, this seems to fix my needs, if I fix the small issues, or do you know any others?

**Comment by dbousamra** [comment]
I would advise against using this for anything serious. It was written for
a uni assignment, and whilst it works in a basic fashion its not really a
production ready library.

What about dropping in lucene and using the in memory stuff?

**Comment by PhilAndrew** [comment]
That's a good idea for in memory, so based on what you said I just searched and found Lucene has the MemoryIndex class. 

http://lucene.apache.org/core/4_6_0/memory/org/apache/lucene/index/memory/MemoryIndex.html

A Scala wrapper for Lucene.

https://github.com/gilt/lib-lucene-sugar

Some code examples.

http://www.massapi.com/class/me/MemoryIndex.html
